public class OsmObjectKey 
{

	final static byte Item_Unknown = 0;
	final static byte Item_Node = 1;
	final static byte Item_Way = 2;
	final static byte Item_Relation = 3;

	private byte  item_type;
	private String item_id;

	public OsmObjectKey( byte passed_item_type, String passed_item_id ) 
	{
		item_type = passed_item_type;
		item_id = passed_item_id;
	}

/* ------------------------------------------------------------------------------
 * Generated by Eclipse and not modified.
 * @see java.lang.Object#hashCode()
 * ------------------------------------------------------------------------------ */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((item_id == null) ? 0 : item_id.hashCode());
		result = prime * result + item_type;
		return result;
	}

/* ------------------------------------------------------------------------------
 * Generated by Eclipse and not modified.
 * This is here so that when we check that one OsmObjectKey matches another we
 * check the contents and not just that the objects themselves are the same object. 
 * 
 * @see java.lang.Object#equals(java.lang.Object)
 * ------------------------------------------------------------------------------ */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OsmObjectKey other = (OsmObjectKey) obj;
		if (item_id == null) {
			if (other.item_id != null)
				return false;
		} else if (!item_id.equals(other.item_id))
			return false;
		if (item_type != other.item_type)
			return false;
		return true;
	}

	byte get_item_type()
	{
		return item_type;
	}

	void set_item_type( byte passed_item_type )
	{
		item_type = passed_item_type;
	}

	String get_item_id()
	{
		return item_id;
	}

	void set_item_id( String passed_item_id )
	{
		item_id = passed_item_id;
	}

}
